### ISSUE TITLE
Missing files after publishing from local machine (after git clone)

### ISSUE THREAD

**Issue by drptbl** [yovanoc/mailsac#12]
Hey,

I'm not able to publish this module successfully after cloning.

`dist` folder is missing some files and `src` folder (it's present when using official npm `mailsac` module, but not present if you clone this repository and publish it yourself on npm).

What is the release process? `npm publish` is not enough.

Cheers,
Jakub.

cc @yovanoc

**Comment by yovanoc** [comment]
Show me your error, I used to do `yarn publish` but I think you just doesn't have rights to publish to my npm account, thats it

**Comment by drptbl** [comment]
@yovanoc 
I've forked your project, changed the timeout to 30 seconds and updated dependencies.
https://github.com/drptbl/mailsac

I've also changed the name from `mailsac` to `@drptbl/mailsac` to make it scoped package.
Then I've republished it on my own npm.

After I require `@drptbl/mailsac` and install it, I can see difference in files between my published package and yours. For example in `dist` folder there is no `src` folder, but in yours official `mailsac` npm module, `src` folder is present.

All I do is `npm publish` - it builds the package and publishes it.

When trying to require `@drptbl/mailsac` I get following error:
```
Error: Cannot find module '@drptbl/mailsac'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/.../utils.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/.../e2e.base.conf.js:6:34)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
error Command failed with exit code 1.                                                                                                             
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 
```
It's related to missing files after publishing. That's why it doesn't work.

Happy to do a PR with my changes after I can test if it works properly.

**Comment by yovanoc** [comment]
I will look into that very soon, This package need a little cleanup yes

**Comment by drptbl** [comment]
@yovanoc Thank you 🎉 .
